import type { Metadata } from 'next';
export const dynamic = 'force-dynamic';
import { MagneticButton } from '@/components/MagneticButton';
import { SectionHeader } from '@/components/SectionHeader';
import { ServiceBlock } from '@/components/ServiceBlock';
import { ProjectShowcase } from '@/components/ProjectShowcase';
import { TestimonialSlider } from '@/components/TestimonialSlider';
import { CTASection } from '@/components/CTASection';
import { ImageReveal } from '@/components/ImageReveal';
import { services, projects } from '@/lib/data';

export const metadata: Metadata = { title:'Startseite', description:'Premium Branding, moderne Firmenkleidung, Textildruck und visuelle Identitäten aus Duisburg.' };
export default function Home(){return <main><section className="relative flex min-h-screen items-end overflow-hidden pb-12 pt-28"><div className="absolute inset-0 -z-10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_20%,rgba(215,198,175,.18),transparent_36%),linear-gradient(160deg,#0b0b0a,#171512_54%,#0b0b0a)]"/><div className="absolute right-8 top-28 h-[54vh] w-[34vw] min-w-[260px] rounded-[2rem] border border-cream/10 bg-cream/5 shadow-editorial"/></div><div className="luxury-container"><p className="mb-8 text-xs uppercase tracking-[.34em] text-sand">Creative Direction / Fashion Branding / Duisburg</p><h1 className="editorial-title max-w-7xl">Moderne Marken brauchen mehr als nur Design.</h1><div className="mt-10 grid gap-8 md:grid-cols-[.8fr_1.2fr]"><div className="flex gap-4"><MagneticButton href="/kontakt">Projekt anfragen</MagneticButton><MagneticButton href="/leistungen" variant="dark">Leistungen entdecken</MagneticButton></div><p className="max-w-2xl text-xl leading-8 muted">THÈA RA MODE & DESIGN entwickelt hochwertige Firmenkleidung, Branding und visuelle Identitäten für moderne Unternehmen.</p></div></div></section><section className="section-pad"><SectionHeader eyebrow="Studio Expertise" title="Unsere Leistungen" text="Von gestickter Mitarbeiterbekleidung bis zur vollständigen Markenidentität: Jede Anwendung wird als Teil eines hochwertigen visuellen Systems gedacht."/>{services.map((s,i)=><ServiceBlock key={s.slug} service={s} index={i}/>)}</section><section className="section-pad bg-[#100f0e]"><SectionHeader eyebrow="Portfolio" title="Referenzprojekte" text="Fiktive Case Studies zeigen, wie Logo, Textil, Print und Raumwirkung zu einem konsistenten Markenauftritt werden."/>{projects.slice(0,3).map((p,i)=><ProjectShowcase key={p[0]} project={p} index={i}/>)}</section><section className="section-pad"><SectionHeader eyebrow="Warum THÈA RA" title="Präzision in Material, Marke und Wirkung."/><div className="luxury-container grid gap-6 md:grid-cols-3">{['Hochwertige Materialien statt Wegwerf-Merch.','Editoriales Branding statt austauschbarer Vorlagen.','Lokale Nähe in Duisburg mit Anspruch für Deutschland.'].map(x=><div key={x} data-gsap-reveal className="rounded-[1.5rem] border border-cream/10 p-8 text-2xl leading-9">{x}</div>)}</div></section><section className="section-pad"><SectionHeader eyebrow="Stimmen" title="Kundenstimmen"/><TestimonialSlider/></section><section className="section-pad"><div className="luxury-container grid gap-8 md:grid-cols-2"><ImageReveal label="TEXTILE CLOSEUP"/><ImageReveal label="PREMIUM PAPER"/></div></section><CTASection/></main>}
